### ISSUE TITLE
Turbine prevents tomcat shutdown

### ISSUE THREAD

**Issue by jeffastorey** [Netflix/Turbine#48]
I have Turbine deployed to a tomcat server, and when I run the shutdown.sh script, tomcat does not shutdown. The only app running in the server is Turbine. I am using the 1.0.0 version.

**Comment by jeffastorey** [comment]
There appears to be a deadlock on shutdown. Relevant part of thread dump shown below

# Found one Java-level deadlock:

"pool-4-thread-1":
  waiting to lock monitor 0x00007f9214003238 (object 0x00000007aaf375c8, a org.apache.tomcat.util.net.SocketWrapper),
  which is held by "http-bio-8080-exec-1"
"http-bio-8080-exec-1":
  waiting to lock monitor 0x00007f92129a19a8 (object 0x00000007ac9e46d8, a com.netflix.turbine.streaming.servlet.SynchronizedHttpServletResponse),
  which is held by "pool-4-thread-1"

# Java stack information for the threads listed above:

"pool-4-thread-1":
    at org.apache.tomcat.util.net.JIoEndpoint.processSocketAsync(JIoEndpoint.java:560)
    - waiting to lock <0x00000007aaf375c8> (a org.apache.tomcat.util.net.SocketWrapper)
    at org.apache.coyote.AbstractProcessor.setErrorState(AbstractProcessor.java:84)
    at org.apache.coyote.http11.AbstractHttp11Processor.action(AbstractHttp11Processor.java:802)
    at org.apache.coyote.Response.action(Response.java:172)
    at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:363)
    at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:331)
    at org.apache.catalina.connector.Response.flushBuffer(Response.java:610)
    at org.apache.catalina.connector.ResponseFacade.flushBuffer(ResponseFacade.java:306)
    at com.netflix.turbine.streaming.servlet.SynchronizedHttpServletResponse.flushBuffer(SynchronizedHttpServletResponse.java:79)
    - locked <0x00000007ac9e46d8> (a com.netflix.turbine.streaming.servlet.SynchronizedHttpServletResponse)
    at com.netflix.turbine.streaming.servlet.TurbineStreamServlet$ServletStreamHandler.writeData(TurbineStreamServlet.java:201)
    at com.netflix.turbine.streaming.TurbineStreamingConnection.writeToStream(TurbineStreamingConnection.java:385)
    at com.netflix.turbine.streaming.TurbineStreamingConnection.handleData(TurbineStreamingConnection.java:284)
    at com.netflix.turbine.handler.HandlerQueueTuple$PerHandlerDispatcher.doWork(HandlerQueueTuple.java:258)
    at com.netflix.turbine.utils.WorkerThread$1.call(WorkerThread.java:145)
    at com.netflix.turbine.utils.WorkerThread$1.call(WorkerThread.java:138)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

"http-bio-8080-exec-1":
    at com.netflix.turbine.streaming.servlet.SynchronizedHttpServletResponse.getWriter(SynchronizedHttpServletResponse.java:102)
    - waiting to lock <0x00000007ac9e46d8> (a com.netflix.turbine.streaming.servlet.SynchronizedHttpServletResponse)
    at com.netflix.turbine.streaming.servlet.TurbineStreamServlet$ServletStreamHandler.noData(TurbineStreamServlet.java:225)
    at com.netflix.turbine.streaming.TurbineStreamingConnection.waitOnConnection(TurbineStreamingConnection.java:214)
    at com.netflix.turbine.streaming.servlet.TurbineStreamServlet.streamFromCluster(TurbineStreamServlet.java:136)
    at com.netflix.turbine.streaming.servlet.TurbineStreamServlet.doGet(TurbineStreamServlet.java:98)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
    - locked <0x00000007aaf375c8> (a org.apache.tomcat.util.net.SocketWrapper)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)

**Comment by benjchristensen** [comment]
At Netflix we never shut down an app server "gracefully", we always kill and restart a JVM, so "clean shutdown" has never been tested or used by us.

If you find a fix you'd like to make go ahead and submit a PR.

**Comment by jeffastorey** [comment]
Ok, thanks. I'll take a look and see if it's worth the effort.

**Comment by jeffastorey** [comment]
It doesn't seem like the deadlock happens every time, but the InstanceMonitor does not shut down cleanly and that does prevent the app from shutting down cleanly. I have created a PR for that. https://github.com/Netflix/Turbine/pull/49
